### ISSUE TITLE
It no longer compiles on ARM on version 0.16

### ISSUE THREAD

**Issue by varosi** [haskell-crypto/cryptonite#90] opened 2016-06-09 09:42 UTC
GHC 7.10.2, Debian Jessie, ARMv7, gcc (Debian 4.9.2-10) 4.9.2

> [103 of 103] Compiling Crypto.Cipher.AES ( Crypto/Cipher/AES.hs, dist/build/Crypto/Cipher/AES.o )
> cbits/cryptonite_rdrand.c: In function ‘cryptonite_cpu_has_rdrand’:
> 
> cbits/cryptonite_rdrand.c:40:2:
>      error: impossible constraint in ‘asm’
>       **asm** volatile ("cpuid": "=a" (ax), "=b" (bx), "=c" (cx), "=d" (dx) : "a" (func));
>       ^
> Failed to install cryptonite-0.16

**Comment by varosi** [comment] 2016-06-09 10:22
cryptonite-0.15 works fine

**Comment by centromere** [comment] 2016-06-09 13:00
Possible duplicate of #88.

**Comment by vincenthz** [comment] 2016-06-13 04:55
hm. fixed in 32aec08dbfe04de101ed7292a5ec2aa385cfb990. @centromere: looks like you removed the x86_64 guard that was present. rdrand shouldn't be tried on anything non-x86

**Closed as completed by vincenthz** 2016-06-13 04:55 UTC
Labels: duplicate

**Comment by centromere** [comment] 2016-06-13 05:20
@vincenthz The reason for [this change](https://github.com/haskell-crypto/cryptonite/commit/9dcef3451daa24319fd352a0d19ed9ab8f60422d) was that, if I turned off rdrand, `ARCH_X86_64` would never get defined. It doesn't seem logical to me that x86_64 support would be predicated upon rdrand.

The PR you just merged in is similar to what I proposed in the [rdrand-fix](https://github.com/haskell-crypto/cryptonite/commit/43b4b7e0dbfab08cbbf3c54bbc5816153450363c) branch.

**Comment by vincenthz** [comment] 2016-06-13 05:31
@centromere: the first part of the change make perfect sense, indeed X86_64 support should have been separate just like you made it. I missed the side effect of moving it instead of copying it.
